#include "Token.h"


namespace epi {

const std::map<const std::string, TokenType> Keywords = {
        { "auto",           TokenType::Auto },
        { "break",          TokenType::Break },
        { "case",           TokenType::Case },
        { "char",           TokenType::Char },
        { "const",          TokenType::Const },
        { "continue",       TokenType::Continue },
        { "default",        TokenType::Default },
        { "do",             TokenType::Do },
        { "double",         TokenType::Double },
        { "else",           TokenType::Else },
        { "enum",           TokenType::Enum },
        { "extern",         TokenType::Extern },
        { "float",          TokenType::Float },
        { "for",            TokenType::For },
        { "goto",           TokenType::Goto },
        { "if",             TokenType::If },
        { "inline",         TokenType::Inline },
        { "int",            TokenType::Int },
        { "long",           TokenType::Long },
        { "register",       TokenType::Register },
        { "restrict",       TokenType::Restrict },
        { "return",         TokenType::Return },
        { "short",          TokenType::Short },
        { "signed",         TokenType::Signed },
        { "sizeof",         TokenType::Sizeof },
        { "static",         TokenType::Static },
        { "struct",         TokenType::Struct },
        { "switch",         TokenType::Switch },
        { "typedef",        TokenType::Typedef },
        { "union",          TokenType::Union },
        { "unsigned",       TokenType::Unsigned },
        { "void",           TokenType::Void },
        { "volatile",       TokenType::Volatile },
        { "while",          TokenType::While },
        { "_Alignas",       TokenType::Alignas },
        { "_Alignof",       TokenType::Alignof },
        { "_Atomic",        TokenType::Atomic },
        { "_Bool",          TokenType::Bool },
        { "_Complex",       TokenType::Complex },
        { "_Generic",       TokenType::Generic },
        { "_Imaginary",     TokenType::Imaginary },
        { "_Noreturn",      TokenType::Noreturn },
        { "_Static_assert", TokenType::StaticAssert },
        { "_Thread_local",  TokenType::ThreadLocal },
};

const std::map<const std::string, TokenType> Punctuators = {
    { "[",   TokenType::LBracket },
    { "]",   TokenType::RBracket },
    { "(",   TokenType::LParen },
    { ")",   TokenType::RParen },
    { "{",   TokenType::LBrace },
    { "}",   TokenType::RBrace },
    { ".",   TokenType::Dot },
    { "->",  TokenType::Arrow },
    { "++",  TokenType::Incr },
    { "--",  TokenType::Decr },
    { "&",   TokenType::Ampersand },
    { "*",   TokenType::Asterisk },
    { "+",   TokenType::Plus },
    { "-",   TokenType::Minus },
    { "~",   TokenType::Tilde },
    { "!",   TokenType::Exclamation },
    { "/",   TokenType::Div },
    { "%",   TokenType::Mod },
    { "<<",  TokenType::LShift },
    { ">>",  TokenType::RShift },
    { "<",   TokenType::Less },
    { ">",   TokenType::Greater },
    { "<=",  TokenType::LessEqual },
    { ">=",  TokenType::GreaterEqual },
    { "==",  TokenType::Equal },
    { "!=",  TokenType::NotEqual },
    { "^",   TokenType::BinXor },
    { "|",   TokenType::BinOr },
    { "&&",  TokenType::LogicalAnd },
    { "||",  TokenType::LogicalOr },
    { "?",   TokenType::Question },
    { ":",   TokenType::Colon },
    { ";",   TokenType::SemiColon },
    { "...", TokenType::Ellipsis },
    { "=",   TokenType::Assign },
    { "*=",  TokenType::IMul },
    { "/=",  TokenType::IDiv },
    { "%=",  TokenType::IMod },
    { "+=",  TokenType::IPlus },
    { "-=",  TokenType::IMinus },
    { "<<=", TokenType::ILShift },
    { ">>=", TokenType::IRShift },
    { "&=",  TokenType::IAnd },
    { "^=",  TokenType::IXor },
    { "|=",  TokenType::IOr },
    { ",",   TokenType::Comma },
    { "#",   TokenType::Hashtag },
    { "##",  TokenType::HHashtag },
};


const std::map<TokenType, TokenInfo> TokenData = {
        { TokenType::Invalid, { "<Invalid token>" } },
        { TokenType::Auto, { "auto", TokenClass::Keyword } },
        { TokenType::Break, { "break", TokenClass::Keyword } },
        { TokenType::Case, { "case", TokenClass::Keyword } },
        { TokenType::Char, { "char", TokenClass::Keyword } },
        { TokenType::Const, { "const", TokenClass::Keyword } },
        { TokenType::Continue, { "continue", TokenClass::Keyword } },
        { TokenType::Default, { "default", TokenClass::Keyword } },
        { TokenType::Do, { "do", TokenClass::Keyword } },
        { TokenType::Double, { "double", TokenClass::Keyword } },
        { TokenType::Else, { "else", TokenClass::Keyword } },
        { TokenType::Enum, { "enum", TokenClass::Keyword } },
        { TokenType::Extern, { "extern", TokenClass::Keyword } },
        { TokenType::Float, { "float", TokenClass::Keyword } },
        { TokenType::For, { "for", TokenClass::Keyword } },
        { TokenType::Goto, { "goto", TokenClass::Keyword } },
        { TokenType::If, { "if", TokenClass::Keyword } },
        { TokenType::Inline, { "inline", TokenClass::Keyword } },
        { TokenType::Int, { "int", TokenClass::Keyword } },
        { TokenType::Long, { "long", TokenClass::Keyword } },
        { TokenType::Register, { "register", TokenClass::Keyword } },
        { TokenType::Restrict, { "restrict", TokenClass::Keyword } },
        { TokenType::Return, { "return", TokenClass::Keyword } },
        { TokenType::Short, { "short", TokenClass::Keyword } },
        { TokenType::Signed, { "signed", TokenClass::Keyword } },
        { TokenType::Sizeof, { "sizeof", TokenClass::Keyword } },
        { TokenType::Static, { "static", TokenClass::Keyword } },
        { TokenType::Struct, { "struct", TokenClass::Keyword } },
        { TokenType::Switch, { "switch", TokenClass::Keyword } },
        { TokenType::Typedef, { "typedef", TokenClass::Keyword } },
        { TokenType::Union, { "union", TokenClass::Keyword } },
        { TokenType::Unsigned, { "unsigned", TokenClass::Keyword } },
        { TokenType::Void, { "void", TokenClass::Keyword } },
        { TokenType::Volatile, { "volatile", TokenClass::Keyword } },
        { TokenType::While, { "while", TokenClass::Keyword } },
        { TokenType::Alignas, { "_AlignAs", TokenClass::Keyword } },
        { TokenType::Alignof, { "_AlignOf", TokenClass::Keyword } },
        { TokenType::Atomic, { "_Atomic", TokenClass::Keyword } },
        { TokenType::Bool, { "_Bool", TokenClass::Keyword } },
        { TokenType::Complex, { "_Complex", TokenClass::Keyword } },
        { TokenType::Generic, { "_Generic", TokenClass::Keyword } },
        { TokenType::Imaginary, { "_Imaginary", TokenClass::Keyword } },
        { TokenType::Noreturn, { "_NoReturn", TokenClass::Keyword } },
        { TokenType::StaticAssert, { "_Static_assert", TokenClass::Keyword } },
        { TokenType::ThreadLocal, { "_Thread_local", TokenClass::Keyword } },
        { TokenType::LBracket, { "[", TokenClass::Punctuator } },
        { TokenType::RBracket, { "]", TokenClass::Punctuator } },
        { TokenType::LParen, { "(", TokenClass::Punctuator } },
        { TokenType::RParen, { ")", TokenClass::Punctuator } },
        { TokenType::LBrace, { "{", TokenClass::Punctuator } },
        { TokenType::RBrace, { "}", TokenClass::Punctuator } },
        { TokenType::Dot, { ".", TokenClass::Punctuator } },
        { TokenType::Arrow, { "->", TokenClass::Punctuator } },
        { TokenType::Incr, { "++", TokenClass::Punctuator } },
        { TokenType::Decr, { "--", TokenClass::Punctuator } },
        { TokenType::Ampersand, { "&", TokenClass::Punctuator } },
        { TokenType::Asterisk, { "*", TokenClass::Punctuator } },
        { TokenType::Plus, { "+", TokenClass::Punctuator } },
        { TokenType::Minus, { "-", TokenClass::Punctuator } },
        { TokenType::Tilde, { "~", TokenClass::Punctuator } },
        { TokenType::Exclamation, { "!", TokenClass::Punctuator } },
        { TokenType::Div, { "/", TokenClass::Punctuator } },
        { TokenType::Mod, { "%", TokenClass::Punctuator } },
        { TokenType::LShift, { "<<", TokenClass::Punctuator } },
        { TokenType::RShift, { ">>", TokenClass::Punctuator } },
        { TokenType::Less, { "<", TokenClass::Punctuator } },
        { TokenType::Greater, { ">", TokenClass::Punctuator } },
        { TokenType::LessEqual, { "<=", TokenClass::Punctuator } },
        { TokenType::GreaterEqual, { ">=", TokenClass::Punctuator } },
        { TokenType::Equal, { "==", TokenClass::Punctuator } },
        { TokenType::NotEqual, { "!=", TokenClass::Punctuator } },
        { TokenType::BinXor, { "^", TokenClass::Punctuator } },
        { TokenType::BinOr, { "|", TokenClass::Punctuator } },
        { TokenType::LogicalAnd, { "&&", TokenClass::Punctuator } },
        { TokenType::LogicalOr, { "||", TokenClass::Punctuator } },
        { TokenType::Question, { "?", TokenClass::Punctuator } },
        { TokenType::Colon, { ":", TokenClass::Punctuator } },
        { TokenType::SemiColon, { ";", TokenClass::Punctuator } },
        { TokenType::Ellipsis, { "...", TokenClass::Punctuator } },
        { TokenType::Assign, { "=", TokenClass::Punctuator } },
        { TokenType::IMul, { "*=", TokenClass::Punctuator } },
        { TokenType::IDiv, { "/=", TokenClass::Punctuator } },
        { TokenType::IMod, { "%=", TokenClass::Punctuator } },
        { TokenType::IPlus, { "+=", TokenClass::Punctuator } },
        { TokenType::IMinus, { "-=", TokenClass::Punctuator } },
        { TokenType::ILShift, { "<<=", TokenClass::Punctuator } },
        { TokenType::IRShift, { ">>=", TokenClass::Punctuator } },
        { TokenType::IAnd, { "&=", TokenClass::Punctuator } },
        { TokenType::IXor, { "^=", TokenClass::Punctuator } },
        { TokenType::IOr, { "|=", TokenClass::Punctuator } },
        { TokenType::Comma, { ",", TokenClass::Punctuator } },
        { TokenType::Hashtag, { "#", TokenClass::Punctuator } },
        { TokenType::HHashtag, { "##", TokenClass::Punctuator } },
};

}