#ifndef EPICALYX_FLAGS_H
#define EPICALYX_FLAGS_H

#define VERBOSITY_ALL 0
#define VERBOSITY_DEBUG 1
#define VERBOSITY_INFO 2
#define VERBOSITY_WARN 3
#define VERBOSITY_ERROR 4
#define VERBOSITY_MAX VERBOSITY_ERROR

#define COMPONENT_TOKENIZER 1
#define COMPONENT_PARSER 2

#define COMPONENT_FLAGS (COMPONENT_TOKENIZER | COMPONENT_PARSER)

#endif //EPICALYX_FLAGS_H
