#ifndef EPICALYX_FLAGS_H
#define EPICALYX_FLAGS_H

#define VERBOSITY_ALL 0
#define VERBOSITY_DEBUG 1
#define VERBOSITY_INFO 2
#define VERBOSITY_WARN 3
#define VERBOSITY_ERROR 4
#define VERBOSITY_MAX VERBOSITY_ERROR


#endif //EPICALYX_FLAGS_H
